apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}
  namespace: {{ cookiecutter.k8s_namespace }}
spec:
  selector:
    app: {{ cookiecutter.project_slug }}
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
